version: "3"
services:

  web:
    container_name: skyloov
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env  
    ports:
      - "0.0.0.0:8000:8000"
    command: bash -c  "python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: skyloov-db
    restart: always
    environment:
      - MYSQL_DATABASE=tg_db
      - MYSQL_ROOT_PASSWORD=password  
    
    volumes:
      - ./dbdata:/var/lib/mysql

    