apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    deployments: redis-skyloov
  name: redis-skyloov
  namespace: skyloov
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      pod: redis-skyloov
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod: redis-skyloov
    spec:
      containers:
        - image: redis
          imagePullPolicy: Always
          name: skyloov
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
