apiVersion: v1
kind: Service
metadata:
  name: redis-service-skyloov
  namespace: skyloov
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    pod: redis-skyloov
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
