apiVersion: v1
data:
  DB_NAME: tg_db
  DB_USER: root
  DB_PASSWORD: password
  DB_HOST: mysql-service
  DB_PORT: "3306"
  EMAIL_HOST_PASSWORD: kluqyiyeecizkova
  EMAIL_HOST_USER: tassihoodz@gmail.com
  SECRET_KEY: 'django-insecure-e9j@1a#v%rw8!&_ihi%7%5*c$26uh^y9sdk%$^y#_6eg2@#4p^'
  REDIS_HOST: redis-service-skyloov
  REDIS_PORT: '6379'
kind: ConfigMap
metadata:
  name: skyloov-configmap
  namespace: skyloov