piVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: skyloov
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: manual
