# Generated by Django 4.2.1 on 2023-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_rating_alter_products_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ARCHIVED', 'Archived'), ('OPEN', 'Open'), ('ABANDONED', 'Abandoned'), ('CONFIRMED', 'Confirmed'), ('DRAFT', 'draft')], default='OPEN', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='carts', to='products.products')),
            ],
        ),
    ]
