# Generated by Django 4.2.1 on 2023-05-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_cart_options_cart_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/'),
        ),
    ]
